services:
  db:
    image: postgres:15-alpine
    container_name: pgsql-db-1
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./postgreSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "${PGPORT}:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${PGDATABASE}
      SPRING_DATASOURCE_USERNAME: ${PGUSER}
      SPRING_DATASOURCE_PASSWORD: ${PGPASSWORD}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend