spring.application.name=segment
server.port=8000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/my_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect